version: '3.1'
services:
  # Ports are not available Error 발생시 (netstat -ano | findstr {PORT NO.} 해도 아무것도 안 나올 때):
  # PowerShell(관리자 권한으로 실행)
  # netsh interface ipv4 show excludedportrange protocol=tcp
  # net stop winnat
  # netsh int ipv4 add excludedportrange protocol=tcp startport={PORT NO.} numberofports=1
  # net start winnat

  # redis command에 redis_password에 password 적기
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --requirepass {redis_password} --port 6379

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.17.4
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - default
    volumes:
      - /elasticsearchvolume
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    user: root

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.13.0
    ports:
      - "5601:5601"
    networks:
      - default
    environment:
      ELASTICSERCH_UTL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200